export { default as AboutPage } from './AboutPage'
export { default as ErrorPage } from './ErrorPage'
export { default as LandingPage } from './LandingPage'
export { default as ThePage } from './ThePage'
export { default as MainView } from './MainView'
